### ISSUE TITLE
create a sandbox to demo the usage

### ISSUE THREAD

**Issue by OlivierJM** [OlivierJM/dynamic-form-fields#11]

**Comment by YoramGondwe** [comment]
What are the requirements for this issue

**Comment by OlivierJM** [comment]
There is an example Folder, it needs to be recreated in codesandbox.io
Maybe with more examples.

**Comment by YoramGondwe** [comment]
okay, that's great should I use my own sandbox for this?

**Comment by OlivierJM** [comment]
Yes, use yours, it doesn't really matter as long it is public

**Comment by YoramGondwe** [comment]
should I post the public link of the sandbox here?

**Comment by YoramGondwe** [comment]
https://codesandbox.io/s/dynamic-forms-89y5r  Sandbox URL

**Comment by OlivierJM** [comment]
Heyyy @YoramGondwe sorry i have been quite on this, let me add the link to the description

**Comment by OlivierJM** [comment]
when you get a chance, correct the wrong spellings in the form.js here https://codesandbox.io/s/dynamic-forms-89y5r?file=/src/forms.js
